language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

deploy:
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -Dmaven.test.redirectTestOutputToFile"
    on:
      branch: master
      tags: true
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -Dmaven.test.redirectTestOutputToFile"
    on:
      branch: develop