# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.12'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: cache-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-${{ runner.os }}-m2

      - name: Clone this repository
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn package
